# Generated by Django 5.0.6 on 2024-07-09 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('display_name', models.CharField()),
                ('title', models.CharField()),
                ('description', models.CharField()),
            ],
        ),
    ]
