# Generated by Django 5.0.6 on 2024-11-12 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vicgovau', '0005_genericstringtaggeditem_alter_dataset_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('format', models.CharField()),
                ('date_created', models.DateTimeField()),
                ('download_link', models.URLField(max_length=255)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vicgovau.dataset')),
            ],
        ),
    ]
