# Generated by Django 5.0.6 on 2024-11-12 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vicgovau', '0006_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='download_link',
            field=models.URLField(max_length=2048),
        ),
    ]
